import { Box, Link } from "@mui/material";
import { Link as RouterLink } from "react-router-dom";
import {
  LegalEmailLink,
  LegalIntro,
  LegalList,
  LegalParagraph,
  LegalSection,
  LegalSubsection,
  LegalTitle,
} from "./legal/LegalTypography";

export const PrivacyPolicy = () => {
  return (
    <Box sx={{ maxWidth: "48rem" }}>
      <LegalTitle>Privacy Policy</LegalTitle>

      <LegalIntro>
        This Privacy Policy describes Our policies and procedures on the collection, use
        and disclosure of Your information when You use the Service and tells You about
        Your privacy rights and how the law protects You. We use Your Personal data to
        provide and improve the Service. By using the Service, You agree to the
        collection and use of information in accordance with this Privacy Policy.
      </LegalIntro>

      <LegalSection>Interpretation and Definitions</LegalSection>

      <LegalSubsection>Interpretation</LegalSubsection>
      <LegalParagraph>
        The words of which the initial letter is capitalized have meanings defined under
        the following conditions. The following definitions shall have the same meaning
        regardless of whether they appear in singular or in plural.
      </LegalParagraph>

      <LegalSubsection>Definitions</LegalSubsection>
      <LegalParagraph>For the purposes of this Privacy Policy:</LegalParagraph>
      <LegalList
        items={[
          <>
            <strong>Company</strong> (referred to as either &quot;the Company&quot;,
            &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to
            Quentox JSC, Sofia, Pimen Zografski 38.
          </>,
          <>
            <strong>Cookies</strong> are small files that are placed on Your computer,
            mobile device or any other device by a website, containing the details of Your
            browsing history on that website among its many uses.
          </>,
          <>
            <strong>Country</strong> refers to: Bulgaria
          </>,
          <>
            <strong>Device</strong> means any device that can access the Service such as a
            computer, a cellphone or a digital tablet.
          </>,
          <>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </>,
          <>
            <strong>Service</strong> refers to the Website.
          </>,
          <>
            <strong>Service Provider</strong> means any natural or legal person who
            processes the data on behalf of the Company. It refers to third-party companies
            or individuals employed by the Company to facilitate the Service, to provide
            the Service on behalf of the Company, to perform services related to the
            Service or to assist the Company in analyzing how the Service is used.
          </>,
          <>
            <strong>Usage Data</strong> refers to data collected automatically, either
            generated by the use of the Service or from the Service infrastructure itself
            (for example, the duration of a page visit).
          </>,
          <>
            <strong>Website</strong> refers to Quentox, accessible from quentox.com
          </>,
          <>
            <strong>You</strong> means the individual accessing or using the Service, or
            the company, or other legal entity on behalf of which such individual is
            accessing or using the Service, as applicable.
          </>,
        ]}
      />

      <LegalSection>Collecting and Using Your Personal Data</LegalSection>

      <LegalSubsection>Personal Data</LegalSubsection>
      <LegalParagraph>
        While using Our Service, We may ask You to provide Us with certain personally
        identifiable information that can be used to contact or identify You. When You
        use our contact form, We collect the information You submit (such as Your name,
        email address, company name, and message). This data is transmitted to and
        processed by Formspree (formspree.io), our third-party form handling provider,
        on Our behalf so that We can respond to Your inquiry.
      </LegalParagraph>

      <LegalSubsection>Usage Data</LegalSubsection>
      <LegalParagraph>
        This website is a static marketing site. We do not run first-party analytics
        and we do not automatically collect usage data such as IP addresses, device
        identifiers, or browsing history for Our own purposes. When You submit the
        contact form, Formspree processes the details You provide. Our hosting
        provider (GitHub Pages) may process standard technical logs in accordance
        with its own policies.
      </LegalParagraph>

      <LegalSection>Tracking Technologies and Cookies</LegalSection>
      <LegalParagraph>
        We do not set first-party analytics or advertising cookies. We do not currently
        use Google Analytics or similar tracking on this site. When You submit the
        contact form, Formspree (formspree.io) may use cookies or similar technologies
        on its own domain in accordance with its policies. For more information, please
        visit our{" "}
        <Link
          component={RouterLink}
          to="/cookies"
          sx={{
            color: "primary.main",
            textDecoration: "none",
            "&:hover": { textDecoration: "underline" },
          }}
        >
          Cookies Policy
        </Link>
        .
      </LegalParagraph>

      <LegalSection>Use of Your Personal Data</LegalSection>
      <LegalParagraph>
        The Company may use Personal Data for the following purposes:
      </LegalParagraph>
      <LegalList
        items={[
          <>
            <strong>To contact You:</strong> To respond to inquiries You send through
            the contact form or by email.
          </>,
          <>
            <strong>To manage Your requests:</strong> To attend and manage Your requests
            to Us.
          </>,
        ]}
      />
      <LegalParagraph>
        We may share Your personal information in the following situations:
      </LegalParagraph>
      <LegalList
        items={[
          <>
            <strong>With Service Providers:</strong> We share contact form submissions
            with Formspree so that We can receive and respond to Your inquiry.
          </>,
          <>
            <strong>With Your consent:</strong> We may disclose Your personal information
            for any other purpose with Your consent.
          </>,
        ]}
      />

      <LegalSection>Retention of Your Personal Data</LegalSection>
      <LegalParagraph>
        The Company will retain Your Personal Data only for as long as is necessary for
        the purposes set out in this Privacy Policy. We will retain and use Your Personal
        Data to the extent necessary to comply with our legal obligations (for example,
        if we are required to retain your data to comply with applicable laws), resolve
        disputes, and enforce our legal agreements and policies.
      </LegalParagraph>
      <LegalSubsection>Transfer of Your Personal Data</LegalSubsection>
      <LegalParagraph>
        Your information, including Personal Data, is processed at the Company&apos;s
        operating offices and in any other places where the parties involved in the
        processing are located. It means that this information may be transferred to —
        and maintained on — computers located outside of Your state, province, country or
        other governmental jurisdiction where the data protection laws may differ than
        those from Your jurisdiction. Your consent to this Privacy Policy followed by Your
        submission of such information represents Your agreement to that transfer. The
        Company will take all steps reasonably necessary to ensure that Your data is
        treated securely and in accordance with this Privacy Policy and no transfer of
        Your Personal Data will take place to an organization or a country unless there
        are adequate controls in place including the security of Your data and other
        personal information.
      </LegalParagraph>

      <LegalSection>Delete Your Personal Data</LegalSection>
      <LegalParagraph>
        You have the right to delete or request that We assist in deleting the Personal
        Data that We have collected about You. Our Service may give You the ability to
        delete certain information about You from within the Service. You may also contact
        Us to request access to, correct, or delete any personal information that You have
        provided to Us. Please note, however, that We may need to retain certain
        information when we have a legal obligation or lawful basis to do so.
      </LegalParagraph>

      <LegalSection>Disclosure of Your Personal Data</LegalSection>

      <LegalSubsection>Law enforcement</LegalSubsection>
      <LegalParagraph>
        Under certain circumstances, the Company may be required to disclose Your
        Personal Data if required to do so by law or in response to valid requests by
        public authorities (e.g. a court or a government agency).
      </LegalParagraph>

      <LegalSubsection>Other legal requirements</LegalSubsection>
      <LegalParagraph>
        The Company may disclose Your Personal Data in the good faith belief that such
        action is necessary to:
      </LegalParagraph>
      <LegalList
        items={[
          "Comply with a legal obligation",
          "Protect and defend the rights or property of the Company",
          "Prevent or investigate possible wrongdoing in connection with the Service",
          "Protect the personal safety of Users of the Service or the public",
          "Protect against legal liability",
        ]}
      />
      <LegalSubsection>Security of Your Personal Data</LegalSubsection>
      <LegalParagraph>
        The security of Your Personal Data is important to Us, but remember that no method
        of transmission over the Internet, or method of electronic storage is 100% secure.
        While We strive to use commercially acceptable means to protect Your Personal
        Data, We cannot guarantee its absolute security.
      </LegalParagraph>

      <LegalSubsection>Links to Other Websites</LegalSubsection>
      <LegalParagraph>
        Our Service may contain links to other websites that are not operated by Us. If
        You click on a third party link, You will be directed to that third party&apos;s
        site. We strongly advise You to review the Privacy Policy of every site You visit.
        We have no control over and assume no responsibility for the content, privacy
        policies or practices of any third party sites or services.
      </LegalParagraph>

      <LegalSubsection>Changes to this Privacy Policy</LegalSubsection>
      <LegalParagraph>
        We may update Our Privacy Policy from time to time. We will notify You of any
        changes by posting the new Privacy Policy on this page. You are advised to review
        this Privacy Policy periodically for any changes. Changes to this Privacy Policy
        are effective when they are posted on this page.
      </LegalParagraph>

      <LegalSubsection>Contact Us</LegalSubsection>
      <LegalParagraph>
        If you have any questions about this Privacy Policy, You can contact us: By email:{" "}
        <LegalEmailLink />
      </LegalParagraph>
    </Box>
  );
};
